name: screen-understanding
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python>=3.10
  
  # PyTorch and CUDA
  - pytorch>=2.8.0
  - torchvision>=0.19.0
  # NOTE: Match this to your installed CUDA runtime. With an NVIDIA driver/toolkit
  # at CUDA 13.0, PyTorch 2.8 wheels/conda packages commonly target CUDA 12.4.
  # Drivers are backward-compatible, so install the CUDA 12.4 runtime below.
  # If you use CPU-only, remove pytorch-cuda.
  - pytorch-cuda=13.0  # Works with CUDA 13.0 drivers
  
  # Core scientific packages
  - numpy>=1.24.0
  - scipy>=1.11.0
  - pandas>=2.1.0
  - matplotlib>=3.8.0
  
  # Image processing
  - pillow>=10.1.0
  - opencv>=4.8.0
  
  # Development tools
  - pip>=23.3
  - jupyter>=1.0.0
  - ipython>=8.18.0
  
  # Additional conda packages
  - tqdm>=4.66.0
  - pyyaml>=6.0
  
  # Install remaining packages via pip
  - pip:
    # Hugging Face ecosystem
    - transformers>=4.36.0
    - accelerate>=0.25.0
    - datasets>=2.16.0
    - huggingface-hub>=0.20.0
    - tokenizers>=0.15.0
    - sentencepiece>=0.1.99
    
    # Detection (YOLO / OmniParser)
    - ultralytics>=8.1.0
    
    # PaddleOCR (requires separate installation)
    - paddlepaddle>=2.5.0
    - paddleocr>=2.7.0
    
    # Additional OCR backends (optional but recommended)
    - pytesseract>=0.3.10
    - easyocr>=1.7.1
    
    # Additional ML packages
    - einops>=0.7.0
    - timm>=0.9.12
    # MXFP4 kernels package
    - kernels>=0.10.0
    
    # Utilities
    - pydantic>=2.5.0
    - aiofiles>=23.2.1
    - protobuf>=4.25.0
    
    # Development tools
    - pytest>=7.4.0
    - pytest-asyncio>=0.21.0
    - black>=23.12.0
    - isort>=5.13.0
    - flake8>=6.1.0
    - mypy>=1.8.0
